### ISSUE TITLE
KeyError: 'unexpected key "densenet1.features.conv0.weight" in state_dict'? 

### ISSUE THREAD

**Issue by MLikelihood** [guanqj932/AG-CNN-for-Chest-X-ray-Image-Classification#1]
The resnet model is updated now

**Comment by somnathrakshit** [comment]
Same here. Please provide the output of pip freeze.

**Comment by somnathrakshit** [comment]
Seems like you gave the link to the densenet model instead of the resnet one

**Comment by guanqj932** [comment]
The resnet model is updated now.

**Comment by guanqj932** [comment]
@MLikelihood @somnathrakshit

**Comment by somnathrakshit** [comment]
Thanks. Will it be possible to provide the code for the Densenet model as well?

**Comment by guanqj932** [comment]
I am sorry the code for densenet could not provide right now. Because
recently something is wrong with my machine and the remote connection is
not available.  The vacation is going on so maybe it needs some time. I
will upload it as soon as possible and let you know.

Somnath Rakshit <notifications@github.com>于2018年8月10日 周五下午4:09写道：

**Comment by somnathrakshit** [comment]
Ok, please let me know when you upload it.

**Comment by guanqj932** [comment]
Hi, Somnath,

I have uploaded the densenet model just now. Thank you for your interests.
Please feel free to contact me if it has any question.

Best Regards,
Qingji

Somnath Rakshit <notifications@github.com> 于2018年8月10日周五 下午8:13写道：

**Comment by somnathrakshit** [comment]
Thanks a lot for the new model. I will study it and contact you regarding my doubts.
